#HAPP

#profile-title: dimonb.profile.v1
#profile-update-interval: 6
#proxy-enable: 1
#tun-enable: 1
#tun-mode: system
#sniffing-enable: 1
#routing-enable: 1

happ://routing/onadd/ewogICJOYW1lIjogIlJVIG1pbmltYWwgd2hpdGVsaXN0IGRpcmVjdCIsCiAgIkxhc3RVcGRhdGVkIjogMTc3NzQwODk2OSwKICAibGFzdFVwZGF0ZWREYXRlIjogMTc3NzQwODk2OSwKCiAgIkdsb2JhbFByb3h5IjogdHJ1ZSwKICAiUm91dGVPcmRlciI6ICJEaXJlY3QtUHJveHktQmxvY2siLAogICJEb21haW5TdHJhdGVneSI6ICJJUElmTm9uTWF0Y2giLAogICJGYWtlRE5TIjogZmFsc2UsCiAgIkZha2VEbnNFbmFibGVkIjogZmFsc2UsCiAgIlVzZUNodW5rRmlsZXMiOiB0cnVlLAoKICAiR2VvaXB1cmwiOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3J1bmV0ZnJlZWRvbS9ydXNzaWEtdjJyYXktcnVsZXMtZGF0L3JlbGVhc2UvZ2VvaXAuZGF0IiwKCiAgIkRpcmVjdFNpdGVzIjogWwogICAgImRvbWFpbjpydSIsCiAgICAiZG9tYWluOtGA0YQiLAogICAgImRvbWFpbjpzdSIKICBdLAoKICAiRGlyZWN0SXAiOiBbCiAgICAiZ2VvaXA6cHJpdmF0ZSIsCiAgICAiZ2VvaXA6cnUiLAogICAgIjEwLjAuMC4wLzgiLAogICAgIjE3Mi4xNi4wLjAvMTIiLAogICAgIjE5Mi4xNjguMC4wLzE2IiwKICAgICIxMDAuNjQuMC4wLzEwIgogIF0sCgogICJQcm94eVNpdGVzIjogW10sCiAgIlByb3h5SXAiOiBbXSwKICAiQmxvY2tTaXRlcyI6IFtdLAogICJCbG9ja0lwIjogW10KfQ==

#fragmentation-enable: 1
#fragmentation-packets: tlshello
#fragmentation-length: 50-100
#fragmentation-interval: 5
#fragmentation-maxsplit: 100-200

PROXY_LIST